### ISSUE TITLE
Create a Game search page for the system (Non-Functional)

### ISSUE THREAD

**Issue by LanternCode** [DMU-CTEC2902-1920/Sample-Text#24]
This page enables the user to search specifically for games. That means the title of the game, its description and eventually mentions of the game in reviews or comments.

**Comment by mreman09** [comment]
Do I just need to create a screen design (pdf file)

**Comment by LanternCode** [comment]
Screen designs are just a tool that may (or may not) help you when creating the actual page. If you find them useful then feel free to create one. If not, feel free to skip it. The actual task tells you to create a .cshtml page that contains the functionality for searching games. There already exists a screen design for this (actually 2). The page must not yet be functional, just containing proper html and styled with css that fits the dmuBlogger theme. Good luck, this is a part of the Final Deliverable milestone and not the Initial Presentation milestone. The sooner you do this the sooner I will be able to assign the task of creating the functionality for it.
