### ISSUE TITLE
Have we have made a mistake agreeing to do an empty project? See page 3 of  Lab 20 documentation.

### ISSUE THREAD

**Issue by JMasiano** [DMU-CTEC2902-1920/Sample-Text#36]
![image](https://user-images.githubusercontent.com/59917965/74471966-0b9ca700-4e99-11ea-87d0-df4d4dc89fd6.png)

**Comment by LanternCode** [comment]
This [project] refers not to the [assignment] project but to the [lab session] project. You can implement login in a multitude of ways, much simpler than this. Show me a single lab session that refers to the [assignment] project. They do help you with understanding code & the MVC flow, but, they do not assist you with the assignment. I think we're on the right track for now.

**Comment by zoemaestra** [comment]
We discussed this previously and agreed that it would be simpler to implement our own login system than it would be to deal with the pre-generated stuff so it's nothing to worry about
