### ISSUE TITLE
The rules of branching

### ISSUE THREAD

**Issue by LanternCode** [DMU-CTEC2902-1920/Sample-Text#39]
Basically these rules are as I understood them from the tutor.

Experimental - Every single commit goes to the experimental branch. Never to dev or master. NEVER. Push ANYTHING into experimental. Then you can start a pull request, and, merge it into dev. No need to consult anything with the rest of the team.

Dev - This branch is the one that features the full code, whether working or not is not important. What is important though is that this branch is what we would call the DEMO branch. Like a live, demo version of the page that we watch for changes and how things interact with each other.

Master - This is the final, LIVE branch. It must be 100% functional in terms of not generating any errors. You can ONLY merge a pull request from dev to master once the pull request has been approved by all team members, probably in the pull request comments. 

DO NOT UPLOAD ANY FILES TO MASTER OR DEV EVEN IF YOU ARE 100% SURE THAT THEY ARE FUNCTIONAL. COMMIT THEM TO EXPERIMENTAL AND START A PULL REQUEST TO MERGE THEM INTO DEV.

ONCE IN THE DEV, IF ENOUGH CHANGES APPEAR, START A PULL REQUEST TO MERGE DEV INTO MASTER. WAIT FOR THE TEAM'S RESPONSE. ONCE EVERYONE HAS ACCEPTED, YOU CAN MERGE INTO MASTER.

Now if you have read all that, understood it and agreed with it, write a comment down below. These rules are my subjective understanding of what the tutor has explained to me during a lab session. We can, also, discard any rules altogether and let anyone do whatever they want. Tutor said it's our choice but that will probably be reflected on our marks.

Remember: If you make a commit you can always AMEND the commit, as if, deleting it. You can also discard any changes if made in an incorrect branch. Git is very powerful.

**Comment by zoemaestra** [comment]
Maybe this should be a wiki page 🤔

**Comment by LanternCode** [comment]
Issue closed. Over 20 unauthorized commits mere made to master branch and totally ignored the rules of branching. With that said, both experimental and dev were removed.
