### ISSUE TITLE
Uneven distribution of work load

### ISSUE THREAD

**Issue by JMasiano** [DMU-CTEC2902-1920/Sample-Text#42]
I have looked over every ones screens and messaged Esosa regarding the workload. Basically, the screens I have been assigned are the most complex. There are time constraints in this project and so we need to work together to assign the tasks more fairly. I see additional complexity being added to pages when its not necessary and this additional complexity appears on the pages that you have allocated to me. The  Game Page has a list of 3 reviews, why even bother when you have a button for reviews any way. Also we have a suggest improvements. It just seems a bit over the top. Not to mention Studio, which Ben and I have mentioned is going to complicate things. I am waiting for feedback from Esosa regarding this issue. I have asked him to review re-distribute the tasks more fairly. @LanternCode

**Comment by LanternCode** [comment]
So basically you have e-mailed your customer to ask for advice on developing the product they wish to buy. A customer will usually have no idea what development process even looks like. Besides, we are only talking about the non-functional screens for now, not the actual functionality. Add to the point, everyone has agreed on the list and there were no issues, so, why mention this now? Do the pages as you see fit, we will add our 3 cents later. Studio will be added only if we have time after all of the coding's done.

**Comment by LanternCode** [comment]
Also, asking the customer to literally manage your development is funny. If I was that customer I would have immediately cancelled my order from that corporation. @benjimaestro @mreman09 @eseosaO

**Comment by LanternCode** [comment]
Also, PLEASE remember that in an actual corporation you will never be asked if you want to work on a certain feature or not. You are assigned a task to do and nobody really cares if you want to do it or not. You either do it or fail your job. The boss will not care whether you consider the workload unequal. They have been programmers for years and years in the past and know the way the assigning should take place. To add to it, why message me and only me? I have not had any impact on your tasks - the team decided what pages they do. Not me. If you wanted me to assign them, sure, no problem. There is still time as the screens are due not for the Initial Presentation but for Final Delivery.

**Comment by LanternCode** [comment]
We _are_ a team on paper but in practice, there's none of that here. Remember that this project _is_ a test of how well can we work on a project. I could have discarded all the progress made by either you or Ben or Reman and said "go with THIS screen design for everything". I didn't. I think we can solve all the difficulties with just enough communication. Attempting to message the CUSTOMER is not only improper but also unprofessional. Attempting to message a supervisor will usually be met with ignorance. A team has a job to do, end it there. Hence why so many games are released unoptimized, glitchy, lacking content and many, many others. Do WE want to be another studio that has nothing to add and yet will only give problems the power to break us apart? The power we artificially grant them?

**Comment by JMasiano** [comment]
The customer is also our tutor. To be fair I'm not happy with this whole set up. I've worked in many environments. I am an engineer by trade, so you don't have teach me about work. In a real environment managers have do have a clue about what the work entails, wouldn't put unnecessary load on people and leave others with nothing. As for the screens, I didn't get a chance to have a think over the work, or discuss it with anyone. As I recall from the lab, when I got to the list of tasks  you and Ben had the list in hand, and Ben said I had to do the left over screens.

**Comment by JMasiano** [comment]
In response to your comment: "There is still time as the screens are due not for the Initial Presentation but for Final Delivery." I agree, so lets work things out. As for commitment and wanting to get this project complete, I am all for that, which is why at the start I said "There are time constraints in this project and so we need to work together to assign the tasks more fairly. "

**Comment by LanternCode** [comment]
No, there is no tutor in this regard. The tutor may help you with issues such as code not working or coding environment being wrongly configured. When it comes to the project, there is no tutor, there is a customer. Once you had seen the list you reacted with "Oh okay this seems fine, I can do that just need to do some extra research on developer". Ben selected screens he liked, Raman selected screens he liked, you got the rest. But I can understand how this is problematic. Honestly, I doubt that anyone has even started working on these screens. Message the team! Talk to them! Do not message the customer or the supervisor trying to say that the team is unfair without previous consultations. We are not enemies. The list is flexible. If you all want so, I can assign the screens ignoring any personal preferences, based just on the subjective opinion of "difficulty".

**Comment by zoemaestra** [comment]
My dudes, it's 1am. Go to sleep.
Secondly, we are only at the prototyping phase - right now, we don't have to do anything other than make the pages look good. For the time being, we don't need to focus on the actual functionality of the pages and we can discuss who does what when we get to that. Looking into the future is good and all, but it can detract from the present.
As for time constraints, we need to keep it in mind more. Technical debt is a real thing, we already have enough to do without needing to deal with that.

@JMasiano if you think the work has been distributed out unevenly, we didn't mean to. We just took from the list of pages we thought we needed and we didn't get complaints at the time but at least it's being brought up now rather than 2 days before the deadline lol. We can always reshuffle this and redistribute so it's optimal for everyone.

It's easy for everyone to get caught up in the stress of deadlines. There's a line between relaxing and losing sight of the goal and getting so stressed we work ourselves into a corner. As long as we're reasonable and keep communication clear, it will be ok!

**Comment by JMasiano** [comment]
Yes I did react with that's OK but as mentioned it was split second decision - based on no past tense. Didn't even think about it. But you are right i will follow it up with the team, as there is still time. I am fair and will only request that from the others. If it turns out they are overwhelmed and I have little to do then I will help take off the extra load. The problem was that, in the lab no one wanted to stay behind and go over the screens apart from me, so the decision was rash and not well thought about. I will request a meeting and go through in detail the different aspects of the screens. But cooperation here is based on hope. This is my experience, so why I consulted the tutor, not the customer, although both are one in this case.

**Comment by JMasiano** [comment]
@benjimaestro  Thanks for the reassurance, I was beginning to think I would be left struggling. It might not be that much work, because its MVC and it makes the database for you, but none of us are really clued up with it at the moment because we've only just started it, so it seems like a lot too do.
